# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.6.dev0+gc75f3af.d20221025"
__version_tuple__ = version_tuple = (0, 6, "dev0", "gc75f3af.d20221025")
